### ISSUE TITLE
object not iterable

### ISSUE THREAD

**Issue by brandon-fsu** [pnnl/socialsim#11]
To Reproduce:
```python
gt_measurements = BaselineMeasurements(ground_truth,platform=platform,content_node_ids=content_ids,user_node_ids = user_ids)
sim_measurements = BaselineMeasurements(simulation,platform=platform,content_node_ids=content_ids, user_node_ids = user_ids)
gt_meas = run_all_measurements(gt_measurements,configs[platform],show=False,plot_dir='gt_output/',
                                plot_flag=True,output_dir='gt_output/')
sim_meas = run_all_measurements(sim_measurements,configs[platform],show=False,plot_dir='sim_output/',
                                plot_flag=True,output_dir='sim_output/')

metrics = run_all_metrics(gt_meas,sim_meas,configs[platform],show=False,plot_dir='plots_output/',
                              plot_flag=True)
```

This also happens if you pass the measurement objects directly rather than the results of the output of running measurements

Output:
Traceback (most recent call last):
  File "run_measurements_and_metrics.py", line 502, in <module>
    main()
  File "run_measurements_and_metrics.py", line 494, in main
    baseline_examples()
  File "run_measurements_and_metrics.py", line 479, in baseline_examples
    plot_flag=True)
  File "run_measurements_and_metrics.py", line 334, in run_all_metrics
    show=show,plot_dir=plot_dir)
  File "run_measurements_and_metrics.py", line 79, in run_metrics
    for node in measurement_on_gt:
TypeError: 'NoneType' object is not iterable

**Comment by emily-grace** [comment]
I added a check that if measurement_on_gt is None it should be converted to an empty dictionary for node-level and community-level measurements.  Let me know if this resolves the issue for you.

**Comment by brandon-fsu** [comment]
That leads to a problem in generate_plot.

Traceback (most recent call last):
  File "run_measurements_and_metrics.py", line 511, in <module>
    main()
  File "run_measurements_and_metrics.py", line 503, in main
    baseline_examples()
  File "run_measurements_and_metrics.py", line 487, in baseline_examples
    plot_flag=True)
  File "run_measurements_and_metrics.py", line 340, in run_all_metrics
    show=show,plot_dir=plot_dir)
  File "run_measurements_and_metrics.py", line 71, in run_metrics
    measurement_name=measurement_name, show=show, plot_dir=plot_dir)
  File "run_measurements_and_metrics.py", line 189, in generate_plot
    keys = simulation.keys()
AttributeError: 'NoneType' object has no attribute 'keys'

**Comment by emily-grace** [comment]
Looks like generate_plot assumed that it would get simulation as input, when it could actually receive either ground truth, simulation, or both.  I just pushed a fix for that.

**Comment by brandon-fsu** [comment]
One more thing. In run_metrics at line 98, there is another place that assumes measurement_on_gt and measurement_on_sim are both objects

**Comment by emily-grace** [comment]
Do you mean the problem is that measurement_on_sim could actually be None there?  I just pushed an update to check the simulation measurement and convert it to an empty dictionary, same as with the ground truth output.

Let me know if there's an additional problem with that line that I'm missing.

**Comment by brandon-fsu** [comment]
Yes, that was the case. It seems to work now, thank you for all your help!

**Comment by brandon-fsu** [comment]
Sorry. I didn't actually look at the output before closing this. It now seems that all metrics are returning None. I can't go back far enough in my terminal to get this error, but I'm pretty sure I saw something about gini expecting two scalars. So there may be type mismatches now?

**Comment by emily-grace** [comment]
Are you just having the problem when you pass the run_all_measurements output to run_all_metrics?  Or are you also getting all Nones when you pass the BaselineMeasurements objects directly?

The input to run_all_metrics for the _simulation_ has to be a Measurements object, not a dictionary of measurement output.  The ground truth can be either a Measurements object or a dictionary of measurement output.  

The idea there was that you would probably want to run metrics against the same ground truth multiple times, so we wanted to add way to store the ground truth measurements without recalculating, but that you would run each simulation once.

**Comment by brandon-fsu** [comment]
You're absolutely right. Sorry. I noticed that before and changed what I was doing but apparently forgot to change it when I copied and pasted the test stuff. Standard ID-10T error.
