### ISSUE TITLE
Github 4 col format leads to copy error on None object

### ISSUE THREAD

**Issue by graysonch** [pnnl/socialsim#21]
Using the legacy 4 column format for Github events causes the legacy code  in BaselineMeasurements to set the object variable self.main_df_opt to None as follows (line 78) Subsequent calls to call copy() on that object (in UserCentricMeasurements.py and ContentCentricMeasurements.py) result in errors. In both cases there is a check for none directly below, suggest checking for "not self.main_df_opt is None" and moving the copy to below this check. I understand 6 columns is now required, but this fix would be helpful in order to run legacy code.
 
BaselineMeasurements.py
```
if platform == 'github' and len(self.main_df.columns) == 6:
            self.main_df_opt = self.main_df.copy()[['action', 'merged']]
            self.main_df = self.main_df.drop(['action', 'merged'], axis=1)
        else:
            self.main_df_opt = None
```
UserCentricMeasurements.py
```
def getUserPullRequestAcceptance(self,eventTypes=['PullRequestEvent'], thresh=2):

        df = self.main_df_opt.copy()

        if not df is None and 'PullRequestEvent' in self.main_df.event.values:
```
ContentCentricMeasurements.py
```
    def getRepoPullRequestAcceptance(self,eventTypes=['PullRequestEvent'],thresh=2):

        '''
        Calculate the proportion of pull requests that are accepted for each repo.
        Question #15 (Optional Measurement)
        Inputs: eventTypes: List of event types to include in the calculation (Should be PullRequestEvent).
                thresh: Minimum number of PullRequests a repo must have to be included in the distribution.
        Output: Data frame with the proportion of accepted pull requests for each repo
        '''
        df = self.main_df_opt.copy()

        #check if optional columns exist
        if not df is None and 'PullRequestEvent' in self.main_df.event.values:
```
Example trace:
```
14 2017-08-30 17:00:00 ERROR:root:Exception in run_Measurements_and_merics::run_all_metrics for: user_trustingness : 'NoneType' object has no attribute 'copy'
Traceback (most recent call last):
  File "/home/social-sim/Documents/Dev_Branch/CP1_Metrics/interfaces/run_measurements_and_metrics.py", line 478, in run_all_metrics
    plot_dir=plot_dir)
  File "/home/social-sim/Documents/Dev_Branch/CP1_Metrics/interfaces/run_measurements_and_metrics.py", line 126, in run_metrics
    measurement_on_sim = run_measurement(simulation,measurement_name,measurement_params,plot_flag=False,simulation=True)
  File "/home/social-sim/Documents/Dev_Branch/CP1_Metrics/interfaces/run_measurements_and_metrics.py", line 235, in run_measurement
    measurement = measurement_function(**measurement_args)
  File "/home/social-sim/Documents/Dev_Branch/CP1_Metrics/socialsim/december-measurements/UserCentricMeasurements.py", line 258, in getUserPullRequestAcceptance
    df = self.main_df_opt.copy()
AttributeError: 'NoneType' object has no attribute 'copy'
```

**Comment by emily-grace** [comment]
I moved the main_df_opt.copy() inside the if statement as you suggested in the most recent update.
